[package]
name = "rinux"
version = "0.1.1"
authors = ["Atomic"]
edition = "2018"
license = "MIT"

[dependencies]
bootloader = { version = "0.9.8", features = ["map_physical_memory"]}
rinuxcore = { path = "./rinux", package = "rinuxcore"}