[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-rinux.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"


[env]
# can be "test", "debug", and "release"
BUILD_TYPE = "debug"