[package]
name = "generic_array"
version = "0.1.0"

[features]
more_lengths = []

[dependencies.std3]
version = "0.1.22"

[dependencies]
typenum = { version = "1.12", features = ["no_std"]}