name: Doc

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

# jobs:
#   release:
#     name: GitHub Pages
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v1

#       - name: Install Rust toolchain
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: nightly
#           profile: minimal
#           override: true
#           components: rustfmt, rust-src

#       - uses: actions/setup-python@v4
#         with:
#           python-version: '3.10' 
#       - run: python x.py init

#       - name: Build Documentation
#         uses: actions-rs/cargo@v1
#         with:
#           command: doc
#           args: --all --no-deps
      
#       - name: Deploy Documentation
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#           publish_branch: gh-pages
#           publish_dir: ./target/doc
#           keep_files: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt, rust-src

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python x.py init
    - name: Build Documentation
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --all --no-deps
    
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './target/x86_64-rinux/doc/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1